using System;
using System.Diagnostics.CodeAnalysis;

namespace Synthesis.Synchronization
{
	/// <summary>
	/// Tags an interface as representing a Sitecore template of a particular version. Used for synchronization checks.
	/// </summary>
	[AttributeUsage(AttributeTargets.Interface, Inherited = false, AllowMultiple = false)]
	public sealed class RepresentsSitecoreTemplateAttribute : Attribute
	{
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="templateId">Sitecore Template ID represented</param>
		/// <param name="versionSignature">Signature of the template version this represents (generated by a TemplateSignatureProvider)</param>
		public RepresentsSitecoreTemplateAttribute(string templateId, string versionSignature)
		{
			TemplateID = templateId;
			VersionSignature = versionSignature;
		}

		/// <summary>
		/// Sitecore Template ID represented
		/// </summary>
		[SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "ID", Justification="Coherent with Sitecore conventions")]
		public string TemplateID { get; private set; }

		/// <summary>
		/// Signature of the template version this represents (generated by a TemplateSignatureProvider)
		/// </summary>
		public string VersionSignature { get; private set; }
	}
}
