using System;
using Sitecore.StringExtensions;

namespace Synthesis.Synchronization
{
	/// <summary>
	/// Tags an interface as representing a Sitecore template of a particular version. Used for synchronization checks.
	/// </summary>
	[AttributeUsage(AttributeTargets.Interface)]
	public sealed class RepresentsSitecoreTemplateAttribute : Attribute
	{
		[Obsolete("This is only here to help upgraders not break the build")]
		public RepresentsSitecoreTemplateAttribute(string templateId, string versionSignature) : this(templateId, versionSignature, null)
		{
		}

		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="templateId">Sitecore Template ID represented</param>
		/// <param name="versionSignature">Signature of the template version this represents (generated by a TemplateSignatureProvider)</param>
		/// <param name="configurationName">Name of the Synthesis configuration the template belongs to</param>
		public RepresentsSitecoreTemplateAttribute(string templateId, string versionSignature, string configurationName)
		{
			TemplateId = templateId;
			VersionSignature = versionSignature;
			ConfigurationName = configurationName.IsNullOrEmpty() ? "Default Configuration" : configurationName;
		}

		/// <summary>
		/// Sitecore Template ID represented
		/// </summary>
		public string TemplateId { get; private set; }

		/// <summary>
		/// Signature of the template version this represents (generated by a TemplateSignatureProvider)
		/// </summary>
		public string VersionSignature { get; private set; }

		public string ConfigurationName { get; private set; }
	}
}
